#remote_theme: pages-themes/cayman@v0.2.0
theme: jekyll-theme-cayman

plugins:
#  - jekyll-remote-theme
  - jekyll-sitemap

title: "Catherine thinks..."
description: "Growing people and organisations for maximum impact"
url: "https://catherinethinks.com"
